### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by neilshevlin** [neilshevlin/sweng-calc-webapp#3] opened 2022-10-20 14:38 UTC
# Summary
Adding the docker image to the application will allow use to start building the docker image and proceed with some of the work regarding the CI/CD pipeline.

## Action
Add a basic Dockerfile to the repo. This basic dockerfile should work for the current version of React. It should be placed in the root directory of the file. Push it to a feature branch of the repo. That is `dev-feature-dockerImage` or something like that. Then we'll try to get the docker image working on other machines before pushing to dev, main, prod etc. 

## Resources
- [Docker Docs] (https://docs.docker.com/)
- [Plural sight article on Docker with React] (https://www.pluralsight.com/guides/using-react.js-with-docker)
- [Dockerising React app Article] (https://mherman.org/blog/dockerizing-a-react-app/)
- [Example on simple project] (https://github.com/thejungwon/docker-reactjs)

## Tasks
- [x] Get Docker file running on some version of the application
- [x] Push docker file to some feature branch.

## Notice
There is one blocking task here. That is issue #2 . You can get something running on your own version of react. It shouldn't vary much, but there might be some versioning issues between what the react app is built for initially vs the docker spec.

**Comment by Indigo-oli** [comment] 2022-10-21 11:44
"Push docker file to some feature branch" task marked as complete.
A Dockerfile and a .dockerignore file have both been created and are on the branch `dev-feature-dockerImage`.

Code for the Docker file was taken from the sources listed above.
As also mentioned above, checking tha tthe Dockerfile and image can be created for some version of the application is blocked by issue #2 . 

Testing of the Dockerfile and ensuring that it works should be done before this issue is marked as closed, and a pull request on the feature branch is made.
I doubt that the Dockerfile won't work, given where the code was taken from, but precautions should be taken anyway. The Dockerfile is simple enough and fully commented, so changing it to suit the application once #2 is complete shouldn't be much work/any trouble - and I can do as soon as needed :)

**Comment by neilshevlin** [comment] 2022-10-24 12:44
The application has been pushed to the dev branch. The dockerfile provided didn't seem to work when I tried to build it for the application. 

Getting an error `ERROR [5/7] RUN npm install --silent ` This might be something to do with Next or the version I was using for the application. I'm using node version 14^. 

[This article](https://www.docker.com/blog/how-to-build-and-run-next-js-applications-with-docker-compose-nginx/) is the most relevant I can find. 

Try pulling the dev branch in to your local machine and getting it to work for the application.

**Comment by Indigo-oli** [comment] 2022-10-24 14:14
Docker file has recieved updates to build and work properly.

The issues was with cb() not running in `npm install`, a known issue that was fixed by using a different version of both `install npm` and node.js.

The file can be built with the command `docker build -t calculator:dev .`, and according to sources above run with the command 'docker run -it --rm -v /app/node_modules -p 3001:3000 -e CHOKIDAR_USEPOLLING=true calculator:dev'

The sites provided above also mention adding the flag '-v ${PWD}:/app' to the command - in order to mount the code into the container "app", however 'PWD' does not work on windows, and so I could not get this to run on my machine.

If operating not on windows, the full docker run command would be: 
'docker run -it --rm -v ${PWD}:/app -v /app/node_modules -p 3001:3000 -e CHOKIDAR_USEPOLLING=true calculator:dev'

A full explanation as to what each flag does can be found [here](https://mherman.org/blog/dockerizing-a-react-app/).

When running, the docker container reports the following commands, before encountering stopping (as far as I can tell)
`> sweng-calc-webapp@0.1.0 start
> next start

sh: next: not found`
Based on my understanding I think this is to do with issues in the webapp and next, as opposed to the dockerfile - however in case the issue is with the file I am not marking this issue as closed, and would appreciate another set of eyes on it.

The (potentially) completed dockerfile can be found in the feature branch 'dev-feature-dockerImage'

**Comment by neilshevlin** [comment] 2022-10-24 16:23
There were a couple of issues on both sides. The Next application had to be updated to output it's file in the correct build directory. But the Docker image needed to expose the port for a port bind. Image should work properly now.

**Closed** 2022-10-24 16:25 UTC
Labels: enhancement
